services:
  motionlabs_backend:
    container_name: motionlabs_backend
    build:
      context: .
      target: development
    command: ["npm", "run", "start:dev"]
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:3000"
    env_file:
      - .env
    depends_on:
      - motionlabs_db
    networks:
      - motionlabs_network

  motionlabs_db:
    container_name: motionlabs_db
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - motionlabs_network

networks:
  motionlabs_network:
    driver: bridge